export const state = {
	imgH: 0,
	imgW: 0,
	startX: 0,
	startY: 0,
	startTop: 0,
	startLeft: 0,
	newTop: 0,
	newLeft: 0,
	rotate: 0,
	scale: 1,
	orientation: null,
	editorLength: 0,
	labelLength: 0,
	imgSrc: null,
	currentRotation: 0,
	currentScale: 1,
};